// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestProject.NewApplication5.Infrastructure.Data;

namespace TestProject.NewApplication5.Infrastructure.Data.Migrations
{
    [DbContext(typeof(NewApplication5DbContext))]
    [Migration("20200411051914_InitDatabase_AddSithLord")]
    partial class InitDatabase_AddSithLord
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestProject.NewApplication5.Domain.SithLords", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<string>("Apprentice")
                        .IsRequired();

                    b.Property<string>("Master")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("SithLords","dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
